[package]
name = "contracts"
version = "0.1.0"

[dependencies]
starknet = "2.6.4"

[dependencies.openzeppelin]
git = "https://github.com/OpenZeppelin/cairo-contracts.git"
tag = "v0.14.0"

[dependencies.snforge_std]
git = "https://github.com/foundry-rs/starknet-foundry"
tag = "v0.25.0"

[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = false

[tool.snforge]
exit_first = false
