[package]
name = "contracts"
version = "0.1.0"

[dependencies]
starknet = "2.8.2"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }

[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = false

[tool.snforge]
exit_first = false
